name: My cicd pipeline

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Run Super Linter
        #uses: github/super-linter@v3
        uses: super-linter/super-linter@v6.0.0
        env:
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  